# Generated by Django 2.0.6 on 2018-07-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(default='url', max_length=1000),
            preserve_default=False,
        ),
    ]
