# Generated by Django 2.0.7 on 2018-09-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
