# Generated by Django 2.0.7 on 2018-09-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='facebook',
            field=models.CharField(max_length=1000),
        ),
    ]
