# Generated by Django 2.0.7 on 2018-09-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180904_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='facebook',
        ),
    ]
