# Generated by Django 2.0.7 on 2018-09-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trinionlinemall', '0002_stores_facebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stores',
        ),
    ]
