# Generated by Django 2.0.7 on 2018-09-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('image_link', models.CharField(max_length=2000)),
                ('location', models.TextField(max_length=300)),
                ('phone_number', models.CharField(max_length=10)),
                ('facebook', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
