# Generated by Django 2.0.7 on 2018-09-07 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20180906_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='store_catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.StoreCatagory'),
        ),
    ]
