# Generated by Django 2.0.7 on 2018-07-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manipulator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfiles',
            old_name='description',
            new_name='new_word',
        ),
        migrations.AddField(
            model_name='userfiles',
            name='old_word',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
