# Generated by Django 2.0.7 on 2018-07-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manipulator', '0004_auto_20180716_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
