# Generated by Django 2.0.7 on 2018-07-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_manipulator', '0005_auto_20180716_2342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userfiles',
            new_name='Userfile',
        ),
    ]
