# Generated by Django 2.0.7 on 2018-07-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_manipulator', '0006_auto_20180717_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
