# Generated by Django 2.0.6 on 2018-07-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Life_Products', models.CharField(max_length=100)),
                ('Pension_Products', models.CharField(max_length=100)),
                ('Health_Products', models.CharField(max_length=100)),
                ('Miscellaneous_Products', models.CharField(max_length=100)),
            ],
        ),
    ]
