# Generated by Django 2.0.6 on 2018-07-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_aid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceproducts',
            name='Health_Products',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insuranceproducts',
            name='Life_Products',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insuranceproducts',
            name='Miscellaneous_Products',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insuranceproducts',
            name='Pension_Products',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
