# Generated by Django 2.0.6 on 2018-07-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_aid', '0002_auto_20180705_2320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceProducts',
        ),
    ]
