# Generated by Django 2.0.7 on 2018-07-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_aid', '0004_clientsdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsdatabase',
            name='ADDRESS',
            field=models.TextField(default='Port of Spain ', max_length=1000),
            preserve_default=False,
        ),
    ]
