# Generated by Django 2.0.7 on 2018-07-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_aid', '0005_clientsdatabase_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsdatabase',
            name='ADDRESS',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='clientsdatabase',
            name='CONTACT',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientsdatabase',
            name='MODE_OF_PAYMENT',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientsdatabase',
            name='NAME',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientsdatabase',
            name='OCCUPATION',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientsdatabase',
            name='PDF',
            field=models.FileField(upload_to='pdf/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='clientsdatabase',
            name='POLICY_PROPERTIES',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientsdatabase',
            name='POLICY_TYPE',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
