# Generated by Django 2.0.7 on 2018-09-12 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent_aid', '0006_auto_20180718_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsdatabase',
            name='agent_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
