# Generated by Django 2.0.7 on 2018-09-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180912_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='icon',
            field=models.ImageField(upload_to='images/products/icons/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='images/products//%Y/%m/'),
        ),
    ]
