# Generated by Django 2.0.7 on 2018-09-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180919_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
